### PR TITLE
Feature/layer tabs

### PR DESCRIPTION
**Pull request by mbwatson**
this sets up the dropdown portion of the layer card. the appearance panel has the layer opacity control and will house the color ramp selection. the other tab renders the layer.properties object.

### CODE REVIEW

**Review by PhillipsOwen — APPROVED** [review]
works great. 

the opacity control doesnt do anything for observation points. should the observations even have an opacity control?

**Review by lstillwe — APPROVED** [review]
Looks good!

**Comment by mbwatson** [comment]
> works great.
> 
> the opacity control doesnt do anything for observation points. should the observations even have an opacity control?

i wondered this, too, @PhillipsOwen. what about the color ramp; would the observation layers also not need that? would they need an appearance tab at all? that would be easy to disable or swap for another set of controls for those layers. i could imagine other observation controls, such as dot size and colors maybe?

**Comment by PhillipsOwen** [comment]
> > works great.
> > the opacity control doesnt do anything for observation points. should the observations even have an opacity control?
> 
> i wondered this, too, @PhillipsOwen. what about the color ramp; would the observation layers also not need that? would they need an appearance tab at all? that would be easy to disable or swap for another set of controls for those layers. i could imagine other observation controls, such as dot size and colors maybe?

the point colors are fixed. i dont see a need for a ramp or opacity. i also think that layer should always be on top if the layer is selected.

**Comment by mbwatson** [comment]
> > > works great.
> > > the opacity control doesnt do anything for observation points. should the observations even have an opacity control?
> > 
> > 
> > i wondered this, too, @PhillipsOwen. what about the color ramp; would the observation layers also not need that? would they need an appearance tab at all? that would be easy to disable or swap for another set of controls for those layers. i could imagine other observation controls, such as dot size and colors maybe?
> 
> the point colors are fixed. i dont see a need for a ramp or opacity. i also think that layer should always be on top if the layer is selected.

the colors are fixed, but they don't have to be :smile: . agreed about the observations being on top. i think it makes sense to force the obs layer to the top layer in the logic for our eventual layer group components

**Comment by lstillwe** [comment]
I think it makes sense to add both opacity and color editing for Observation points. Note that there are currently 3 types of stations, so each type should have their own color setting

**Pull request merged**
