### PR TITLE
Issue214 - Update sidebar layer tray to toggle raster layers like the control panel.

### PR DESCRIPTION
**Pull request by lstillwe**
This update causes the sidebar layer tray to toggle raster layer visibility more like radio buttons.
This is how the raster layers are toggled in the control panel.

Please merge and remove branch on approval.

### CODE REVIEW

**Review by PhillipsOwen — COMMENTED** [review]
i am seeing that layers on a model run are sorted (in reverse order) following a control panel advisory decrement.

**Comment by PhillipsOwen** [comment]
are the up/down buttons on each layer card redundant? they no longer seem to have a purpose in light of the new radio button like functionality.

**Comment by lstillwe** [comment]
> i am seeing that layers on a model run are sorted (in reverse order) following a control panel advisory decrement.



> i am seeing that layers on a model run are sorted (in reverse order) following a control panel advisory decrement.

I assume that was originally done so the last layer to be rendered was the one at the top of the defaultModelLayers array.

**Comment by lstillwe** [comment]
> are the up/down buttons on each layer card redundant? they no longer seem to have a purpose in light of the new radio button like functionality.



> are the up/down buttons on each layer card redundant? they no longer seem to have a purpose in light of the new radio button like functionality.

Probably. I consider this fix a temporary step - till issue #215 is done.

**Pull request merged**
